- hosts: prod

  tasks:
    - name: Insert dockerfile
      template:
        src: "Dockerfile.j2"
        dest: "Dockerfile"
        mode: 0644

    - name: Copying docker-compose.yml.j2
      template:
        src: "docker-compose.yml.j2"
        dest: "docker-compose.yml"
        mode: 0644

    - name: Run docker-compose
      shell: "docker-compose up -d"
